spring:
  application:
    name: mySite

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: JJH
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 캐싱 비활성화

  # Email
  mail:
    host: smtp.gmail.com
    port: 587
    username: dlstoddyflcorj@gmail.com
    password: hnbpombfbauuayyt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
    sender-email: dlstoddyflcorj@gmail.com

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

jwt:
  secret: askdjnaskjdkjsdasdfvfvhjtwrfbqkwjbekjqwbehjqwbejhqwbejhqwebjhwqebjhqwbejhqwbejhbqwehjbfjhbqjfhqaskdnsadnkjf
  accessExp : 1800000 # 30 * 60 * 1000 밀리초 (30분)
  refreshExp : 180000000

logging:
  level:
    org.hibernate: info