--------------------------------------------------------
--  DDL for Table EMAIL_VERIFICATION
--------------------------------------------------------

CREATE TABLE "JJH"."EMAIL_VERIFICATION"
(	"EMAIL_ID" NUMBER,
     "EMAIL" VARCHAR2(255 BYTE),
     "EMAIL_STATUS" NUMBER(1,0) DEFAULT 0,
     "CODE" VARCHAR2(6 BYTE),
     "EXPIRATION" TIMESTAMP (6)
) SEGMENT CREATION IMMEDIATE
    PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
            PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007052
--------------------------------------------------------

CREATE UNIQUE INDEX "JJH"."SYS_C007052" ON "JJH"."EMAIL_VERIFICATION" ("EMAIL_ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007053
--------------------------------------------------------

CREATE UNIQUE INDEX "JJH"."SYS_C007053" ON "JJH"."EMAIL_VERIFICATION" ("EMAIL")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMAIL_VERIFICATION
--------------------------------------------------------

ALTER TABLE "JJH"."EMAIL_VERIFICATION" ADD UNIQUE ("EMAIL")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "JJH"."EMAIL_VERIFICATION" ADD PRIMARY KEY ("EMAIL_ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
        STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
        PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
        TABLESPACE "SYSTEM"  ENABLE;
ALTER TABLE "JJH"."EMAIL_VERIFICATION" MODIFY ("EMAIL_STATUS" NOT NULL ENABLE);
ALTER TABLE "JJH"."EMAIL_VERIFICATION" MODIFY ("EMAIL" NOT NULL ENABLE);
